server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.243:32773/learning?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 180000
      connection-test-query: SELECT 1

#myBatis配置
mybatis:
  type-aliases-package: xyz.teew.domain
  mapper-locations: classpath:mapper/*.xml

#mapper配置
mapper:
  mappers: xyz.teew.mapper.BaseMapper
  not-empty: false #比如，判断表达式username!=null时，是否自动追加username!=''的判断
  identity: MYSQL  #数据库方言